// Code generated by goyacc -l -o plexmatch.go plexmatch.y. DO NOT EDIT.
package plexmatch

import __yyfmt__ "fmt"

import (
	"bytes"
	"sort"
)

type PlexMatch struct {
	Title    string
	Show     string
	TMDBID   int
	TVDBID   int
	IMDBID   int
	Year     int
	Season   int
	Episodes []Episode
}

type Episode struct {
	ID      int
	Name    string
	Special bool
}

type yySymType struct {
	yys       int
	plexMatch PlexMatch
	episode   Episode
	episodes  []Episode
	strVal    string
	intVal    int
}

const TitleHint = 57346
const ShowHint = 57347
const SeasonHint = 57348
const YearHint = 57349
const TMDBHint = 57350
const TVDBHint = 57351
const IMDBHint = 57352
const GUIDHint = 57353
const EpisodeHint = 57354
const Special = 57355
const Str = 57356
const Int = 57357
const Float = 57358

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"TitleHint",
	"ShowHint",
	"SeasonHint",
	"YearHint",
	"TMDBHint",
	"TVDBHint",
	"IMDBHint",
	"GUIDHint",
	"EpisodeHint",
	"Special",
	"Str",
	"Int",
	"Float",
	"':'",
	"'t'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

func Marshal(p PlexMatch) []byte {
	buf := bytes.Buffer{}
	if p.Title != "" {
		buf.WriteString(__yyfmt__.Sprintf("title: %s\n\n", p.Title))
	}
	if p.Show != "" {
		buf.WriteString(__yyfmt__.Sprintf("show: %s\n\n", p.Show))
	}
	if p.TMDBID != 0 {
		buf.WriteString(__yyfmt__.Sprintf("tmdbid: %d\n\n", p.TMDBID))
	}
	if p.TVDBID != 0 {
		buf.WriteString(__yyfmt__.Sprintf("tvdbid: %d\n\n", p.TVDBID))
	}
	if p.IMDBID != 0 {
		buf.WriteString(__yyfmt__.Sprintf("imdbid: %d\n\n", p.IMDBID))
	}
	if p.Year != 0 {
		buf.WriteString(__yyfmt__.Sprintf("year: %d\n\n", p.Year))
	}
	if p.Season != 0 {
		buf.WriteString(__yyfmt__.Sprintf("season: %d\n\n", p.Season))
	}
	sort.SliceStable(p.Episodes, func(i, j int) bool {
		if p.Episodes[i].Special {
			return true
		}
		if p.Episodes[j].Special {
			return false
		}
		return p.Episodes[i].ID < p.Episodes[j].ID
	})
	ep := Episode{}
	for _, v := range p.Episodes {
		if v.ID == ep.ID && v.Special == ep.Special {
			continue
		}
		ep = v
		sp := ""
		if v.Special {
			sp = "SP"
		}
		buf.WriteString(__yyfmt__.Sprintf("ep: %s%02d: %s\n", sp, v.ID, v.Name))
	}
	return buf.Bytes()
}

func Unmarshal(data []byte) (PlexMatch, error) {
	l := newLex(data)
	_ = yyParse(l)
	return l.plexMatch, l.err
}

func (p PlexMatch) merge(b PlexMatch) PlexMatch {
	a := p
	if a.Title == "" {
		a.Title = b.Title
	}
	if a.Show == "" {
		a.Show = b.Show
	}
	if a.TMDBID == 0 {
		a.TMDBID = b.TMDBID
	}
	if a.TVDBID == 0 {
		a.TVDBID = b.TVDBID
	}
	if a.IMDBID == 0 {
		a.IMDBID = b.IMDBID
	}
	if a.Year == 0 {
		a.Year = b.Year
	}
	if a.Season == 0 {
		a.Season = b.Season
	}
	a.Episodes = append(a.Episodes, b.Episodes...)
	return a
}

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 48

var yyAct = [...]int8{
	35, 41, 44, 36, 12, 13, 18, 17, 14, 15,
	16, 46, 20, 42, 30, 29, 28, 11, 27, 26,
	25, 24, 23, 40, 43, 39, 38, 37, 34, 33,
	47, 45, 32, 31, 20, 19, 3, 10, 9, 21,
	8, 7, 6, 5, 4, 2, 1, 22,
}

var yyPact = [...]int16{
	0, -1000, 0, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 22, 5, 4, 3, 2, 1, -1, -2, -1000,
	-3, -1000, -1000, 19, 18, 14, 13, -15, 12, 11,
	10, -1000, -1000, -1000, -1000, -1000, -17, -1000, -1000, -4,
	9, -13, 17, -6, -1000, -1000, 16, -1000,
}

var yyPgo = [...]int8{
	0, 46, 45, 36, 44, 43, 42, 41, 40, 38,
	37, 35, 17,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 3, 4, 5, 6, 7, 8, 8, 9, 10,
	12, 12, 11, 11,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 3, 3, 3, 3, 5, 3, 3,
	2, 1, 5, 6,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	-10, -12, 4, 5, 8, 9, 10, 7, 6, -11,
	12, -3, -11, 17, 17, 17, 17, 17, 17, 17,
	17, 14, 14, 15, 15, 15, 18, 15, 15, 15,
	13, 18, 17, 15, 15, 14, 17, 14,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 5, 6, 7, 8, 9,
	10, 11, 0, 0, 0, 0, 0, 0, 0, 21,
	0, 2, 20, 0, 0, 0, 0, 0, 0, 0,
	0, 12, 13, 14, 15, 16, 0, 18, 19, 0,
	0, 0, 0, 0, 17, 22, 0, 23,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 17, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 18,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch = yyDollar[1].plexMatch
			yylex.(*lex).plexMatch = yyVAL.plexMatch
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.plexMatch = yyDollar[1].plexMatch.merge(yyDollar[2].plexMatch)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch = yyDollar[1].plexMatch
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch.Title = yyDollar[1].strVal
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch.Show = yyDollar[1].strVal
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch.TMDBID = yyDollar[1].intVal
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch.TVDBID = yyDollar[1].intVal
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch.IMDBID = yyDollar[1].intVal
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch.Year = yyDollar[1].intVal
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch.Season = yyDollar[1].intVal
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.plexMatch.Episodes = yyDollar[1].episodes
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strVal = yyDollar[3].strVal
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strVal = yyDollar[3].strVal
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.intVal = yyDollar[3].intVal
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.intVal = yyDollar[3].intVal
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.intVal = yyDollar[3].intVal
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.intVal = yyDollar[5].intVal
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.intVal = yyDollar[3].intVal
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.intVal = yyDollar[3].intVal
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.episodes = append(yyDollar[1].episodes, yyDollar[2].episode)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.episodes = append(yyVAL.episodes, yyDollar[1].episode)
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.episode = Episode{ID: yyDollar[3].intVal, Name: yyDollar[5].strVal, Special: false}
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.episode = Episode{ID: yyDollar[4].intVal, Name: yyDollar[6].strVal, Special: true}
		}
	}
	goto yystack /* stack new state and value */
}
